### ISSUE TITLE
Installing v0.9.0 nginx_exporter_nginxinc binaries fails

### ISSUE THREAD

**Issue by skress** [mesaguy/ansible-prometheus#34]
In version 0.9.0 nginx changed the file name schema from ...linux-amd64.tar.gz to ...linux_amd64.tar.gz.

I guess the easiest solution would be to remove all binaries prior to v0.9.0 from `vars/software/nginx-prometheus-exporter_nginxinc.yml` and switch the architecture to the new schema.

I can send a corresponding PR if you like.

**Comment by mesaguy** [comment]
Thanks for the notification, this has been fixed in v0.12.40 with 378b74a
