### ISSUE TITLE
Support for rules.yml file

### ISSUE THREAD

**Issue by tfalkowski-nsidc** [mesaguy/ansible-prometheus#8]
Hey mesaguy,

Thank you for all of your hard work on this code!

Maybe I missed it but I do not see any support for defining a rules.yml file under /etc/prometheus. If i missed it can you point me in the right direction? If I am right, can I make a feature request to support deploying a rules.yml file. I think it could be done similarly to how the prometheus server config file is deployed. 

Thanks.

**Comment by mesaguy** [comment]
Thank you for the kind note! Support for Prometheus 'rules' files is implemented in 0.11.x which will be released within a week. I am currently writing kitchen tests for the 'rules' feature and a few additional features.

**Comment by tfalkowski-nsidc** [comment]
Thank you so much. I look forward to the new release.

Cheers

**Comment by mesaguy** [comment]
The 'rules' management feature has been added with the now released 0.11.x major release

**Comment by tfalkowski-nsidc** [comment]
Hey Mesaguy, 

Thanks for the update. 

-Thomas
