### ISSUE TITLE
Support Percona MongoDB Exporter

### ISSUE THREAD

**Issue by JamesBrickell** [mesaguy/ansible-prometheus#9]
Hi, 
Thanks for all your hard work could it be possible to add support for the Percona MongoDB Exporter.
https://github.com/percona/mongodb_exporter#percona-mongodb-exporter

**Comment by mesaguy** [comment]
Certainly, support for the mongodb_exporter has been added with the recent 0.11.x major release, please find usage [documentation here](https://github.com/mesaguy/ansible-prometheus/blob/master/docs/mongodb_exporter_percona.md)
